# Generated by Django 5.1.7 on 2025-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=9),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
