[project]
name = "hexlet-django-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-bootstrap4>=24.4",
    "django>=5.1.7",
    "django-extensions>=3.2.0"
]
