install:
	poetry install

start:
	poetry run flask --app flask_example/example run --port 8000

debug:
	poetry run flask --app flask_example/example --debug run --port 8000

session-debug:
	poetry run flask --app flask_example/session_example --debug run --port 8000

users-debug:
	poetry run flask --app flask_example/users_handling --debug run --port 8000
