# Generated by Django 5.1.7 on 2025-05-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
